#!/bin/bash

# This script helps you configure your USB dac in mpd.conf if you use Cubox-i ord Odroid-c1+

clear
red='\e[0;31m'
NC='\e[0m'
echo -e "${red}USB DAC CONFIGURATION TOOL FOR ODROID C2${NC}"
echo -e "${red}---------------------------${NC}"
echo -e " "
PS3='Please select the desired configuration: '
options=("Odroid C2" "Default Configuration" "Quit")
select opt in "${options[@]}"
do
    case $opt in
              "Odroid C2")
              sed -i 's/^device.*/device          "hw:0,0"/' /etc/mpd.conf
              systemctl restart mpd
              echo -e "${red}Your USB Dac is now ready to be used with Odroid C2...${NC}"  
              exit
              ;;
              "Default Configuration")
              sed -i 's/^device.*/device          "hw:0,0"/' /etc/mpd.conf
              systemctl restart mpd
              echo -e "${red}Applied default configuration...${NC}"  
              exit
              ;;
              "Quit")
              break
               ;;
               *) echo Invalid option - Please choose 1-3;;
    esac
done
