#!/bin/bash

clear
red='\e[0;31m'
NC='\e[0m'

echo -e "${red}Restoring MPD database...${NC}"
systemctl stop mpd
cp /opt/dbackup/mpd.db /var/lib/mpd/mpd.db
chmod 644 /var/lib/mpd/mpd.db
chown mpd:audio /var/lib/mpd/mpd.db
systemctl start mpd
systemctl daemon-reload
echo -e "${red}MPD database restore finished. You 're ready to go!...${NC}"
