#!/bin/bash
# A simple script to configure Archphile Distribution.
# It's still at a very early stage and it's not yet functional.

# Function for the main menu.
#
function main_menu 
{
	clear
	tput setf 1
	option=0
	until [ "$option" = "4" ]; do
	    
	    echo "############## Archphile Configuration Script v0.1 ##############"
	    echo ""	
		echo "  1.) System Configuration"
		echo "  2.) MPD Configuration"
		echo "  3.) Extra stuff configuration"
		echo "  4.) Exit"
		echo ""
		echo -n "Enter choice: "
		read option
		echo ""
	case $option in
		1 ) system_configuration;;
		2 ) mpd_configuration;;
		3 ) archphile_extra;;
		4 ) tput setf 7; exit;;
		* ) echo "Please enter 1, 2 3 or 4";;
	esac
	done
 }
 
# Function for the system configuration. It will allow the user to
# be able to configure basic stuff like changing the root password
# editing resolv.conf, changing the ntp servers etc.
#
function system_configuration 
{
    clear 	
	tput setf 5	
	option=0
	until [ "$option" = "7" ]; do
		echo "############## Archphile Configuration Script v0.1 ##############"
		echo ""	
		echo "  SYSTEM CONFIGURATION"
		echo ""
		echo "  1.) Change root pasword"
		echo "  2.) Change network configuration"
		echo "  3.) Edit resolv.conf in order to change DNS"
		echo "  4.) Edit fstab in order to configure samba/NFS shares"
		echo "  5.) Edit ntp.conf in order to configure NTP servers"
		echo "  6.) Return to previus menu"
		echo "  7.) Exit"
		echo ""
		echo -n "Enter choice: "
		read option
		echo ""
	case $option in
		1 ) passwd root; tput setf 5;; 
		2 ) nano /etc/netctl/archphile-network; netctl reenable archphile-network; tput setf 5; clear;;
		3 ) nano /etc/resolv.conf; tput setf 5; clear;;
		4 ) nano /etc/fstab; tput setf 5; clear;;
		5 ) nano /etc/ntp.conf; tput setf 5; clear;;
		6 ) clear; break ; tput setf 1;;
		7 ) tput setf 7; exit;;
		* ) echo "Please enter from 1 to 7"; 
	esac

	done
}

# Function for the MPD configuration. It will allow the user to
# choose one of the offered MPD packages to install and edit mpd.conf.
# 
function mpd_configuration 
{
	clear	
	tput setf 2	
	option=0
	until [ "$option" = "4" ]; do
	    echo "############## Archphile Configuration Script v0.1 ##############"
	    echo ""	
		echo "  MPD CONFIGURATION"
		echo ""
		echo "  1.) Choose MPD Package To Install"
		echo "  2.) Edit mpd.conf"
		echo "  3.) Return to previous menu"
		echo "  4.) Exit"
		echo ""
		echo -n "Enter choice: "
		read option
		echo ""
	case $option in
		1 ) mpd_packages;; 
		2 ) mpd_edit;;
		3 ) clear; tput setf 1; break ;;
		4 ) tput setf 7; exit; ;;
		* ) echo "Please enter from 1 to 4"; 
	esac

	done
} 

# Function for the MPD packages installation.
# 
function mpd_packages
{
	clear	
	tput setf 2	
	option=0
	until [ "$option" = "5" ]; do
	    echo "############## Archphile Configuration Script v0.1 ##############"
	    echo ""
		echo "  MPD CONFIGURATION"
		echo ""
		echo "  Choose one of the following packages to install/reinstall:"
		echo ""
		echo "  1.) mpd-archphile"
		echo "  2.) mpd-archphile-minimal"
		echo "  3.) mpd-archphile-native-dsd"
		echo "  4.) mpd-archphile-sacd"
		echo "  5.) Return to previous menu"
		echo ""
		echo -n "Enter choice: "
		read option
		echo ""
	case $option in
			1 ) pacman -Sy mpd-archphile; mpd_post_install;;
			2 ) pacman -Sy mpd-archphile-minimal; mpd_post_install;;
			3 ) pacman -Sy mpd-archphile-native-dsd; mpd_post_install;;
			4 ) pacman -Sy mpd-archphile-sacd; mpd_post_install;;
			5 ) clear; break ;;
			* ) echo "Please enter from 1 to 5";; 
	esac

	done
} 


# Function that is used after the installation of each of the offered MPD packages.
# It calls mpd_device function so that the user will be able to choose between USB/I2S
# and configure both of the above. It also deals with MPD systemd service.
#
function mpd_post_install
{
	mpd_device
	systemctl reenable mpd
	systemctl daemon-reload
	systemctl restart mpd
}

# Function used in mpd_post_install. The user chooses and configure the type of dac to use 
# with Archphile.
#
function mpd_device
{
	option=0
	until [ "$option" = "3" ]; do
		echo "  Please choose your configuration:"
		echo "  1.) USB DAC"
		echo "  2.) I2S DAC"
		echo "  3.) Return to previous menu"
 
		echo -n "Enter choice: "
		read option
		echo ""
	case $option in
		1 ) usb_device;;
		2 ) i2select;;
		3 ) break ;;
		* ) tput setf 3;echo "Please enter 1, 2, or 3";tput setf 3; 
	esac

	done
}

# Function used in mpd_device. The user chooses the type of board and after that mpd.conf is
# updated with the correct alsa device number.
#

function usb_device
{
	option=0
	until [ "$option" = "3" ]; do
		echo "  Please choose your board:"
		echo "  1.) Raspberry Pi 2/3"
		echo "  2.) Odroid C1+/C2"
		echo "  3.) Return to previous menu"
		echo ""
		echo -n "Enter choice: "
		read option
		echo ""
	case $option in
		1 ) break;;
		2 ) sed -i 's/^device          "hw:0,0".*/device          "hw:1,0"/' /etc/mpd.conf;;
		3 ) break;;
		* ) tput setf 3;echo "Please enter from 1 to 3";tput setf 3; 
	esac
	done
 }
 
# Function used at mpd_configuration. It simply allows the user to edit mpd.conf.
#
function mpd_edit
{
	nano /etc/mpd.conf
	systemctl restart mpd
}

#function archphile_extra
#{
#	option=0
#until [ "$option" = "3" ]; do
#echo "  Please choose your board:"
#echo "  1.) Upnp/dlna"
#echo "  2.) Shairport"
#echo "  3.) Spotify"
#echo "  4.) Squeezelite"
#echo "  5.) Return to menu"
#echo ""
#echo -n "Enter choice: "
#read option
#echo ""
#case $option in
#    1 ) upnp_dlna_extra;;
#    2 ) shairport_extra;;
#    3 ) spotify_extra;;
#    4 )
#    * ) tput setf 3;echo "Please enter 1, 2, 3";tput setf 3; 
#esac
#done
#	
#	}

#function upnp_dlna_extra{
#}

#function shairport_extra{
#}

#function spotify_extra{
#}

main_menu
