#!/bin/bash
# this command is used in order to unmute dac and set the volume to 100% during boot
# 
/usr/bin/unmute

# please replace x with the id of your device 
#
# note that usbhid module is completely disabled in latest custom kernel
# and you don't need to apply anyhting
#
#echo -n "x-x.x:x.x" > /sys/bus/usb/drivers/usbhid/unbind

# this command sets deadline scheduler during boot
#
# note that mq-deadline is currently the default scheduler
#
#echo mq-deadline > /sys/block/mmcblk0/queue/scheduler

# this command sets ondemand cpu governor
#
# please do not change governor with latest image
#
#echo ondemand | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor >/dev/null

# this command sets swappiness to 0
#
echo 0 > /proc/sys/vm/swappiness

# commands to change various kernel parameters
# please note that some of them might already have the mentioned value
# feel free to experiment if you know what you' re doing!
#
#echo 1500000 > /proc/sys/kernel/sched_latency_ns
#echo 1000000 > /proc/sys/kernel/sched_rt_period_us
#echo 950000 > /proc/sys/kernel/sched_rt_runtime_us
#echo 1 > /proc/sys/kernel/sched_autogroup_enabled
#echo 10 > /proc/sys/kernel/sched_rr_timeslice_ms
#echo 750000 > /proc/sys/kernel/sched_min_granularity_ns
#echo 1000000 > /proc/sys/kernel/sched_wakeup_granularity_ns

# Disable Odroid C2 heartbeat blue led
echo default-on > /sys/class/leds/c2\:blue\:alive/trigger 

# IRQ affinity optimization
#
/usr/local/bin/irq-archphile

# set various processes to be run on specific cores
# cores 1,2 and 3 are isolated
# core 2 deals with ethernet interrupts
# core 3 deals with USB interrupts
# core 0 deals with the rest
# this is why send mpd (or squeezelite) to isolated core 1
#
sleep 5
taskset -c -a -p 1 $(pidof mpd)
#taskset -c -a -p 1 $(pidof squeezelite)

# wireless connection tweaks
#
#iwconfig wlan0 power off
#iwconfig wlan0 frag 2346
#iwconfig wlan0 rts 2347
#iw reg set GR


